### ISSUE TITLE
EPIC: As user of the web component store, I want to have a preview with various options, to easily see all possibilities of complex components

### ISSUE THREAD

**Issue by Piiit** [noi-techpark/it.bz.opendatahub.webcomponents#174]
- [ ] Allow style sheets in the snippet
- [ ] Allow additional import of JS libraries, for example, vueJS as separate import
- [ ] Allow multiple configurator presets. Example, VKG web component, that has some views: map or table
- [ ] Better JSON support on the configurator
- [ ] Better multiline text support on the configurator
