### ISSUE TITLE
EPIC: as a web component store user I want to have the web component store 2.0 in order to be able to use it in a more intuitive way.

### ISSUE THREAD

**Issue by sseppi** [noi-techpark/it.bz.opendatahub.webcomponents#88]
High Priority. Deadline: 04th of March 2022

Priority has been raised because on the old store there are problems with some web components being displayed badly. i.e. IDM Announcements Component.

This has been externalized to @mmalfertheiner . He will start with it in 2022... we prioritize the Data browser at the moment.

First TODO when starting is to cleanup the tasks in this issue and review the other related issues.

The link to the project plan is:

https://docs.google.com/presentation/d/13AbdNLZSDIPxnJ9ahHRSQ_Wy57gmlwLPZiYpX-XS1t4/edit?usp=sharing

Example:
https://webcomponents.opendatahub.testingmachine.eu/

**OUTDATED COMMENTS**

```
Status: We've got a PR by Konverto. First MVP online, but several issues exist... We have posted them to their Kanban at https://github.com/orgs/noi-techpark/projects/25... Blocked until solved

**TODOS before putting it onto production**


- [ ] Solve #139 
- [ ] Update all stats of all web components
- [ ] Link to the README and License information for each web component
- [ ] Solve #110 
- [ ] Redirect the URLs to the new docker instances
```

**Comment by niettadesantis** [comment]
As said in the today's meeting, @dulvui, if you can complete the task before the 4th of March, it would be very appreciated and as soon you have finished, please let me know. Thank you!
